// ** Auth Endpoints
import { verify } from 'jsonwebtoken'
import { roolink } from '../../../configs/linkConfigs'
export default {
  userloginEndpoint: `${roolink}admin/login`,
  otploginverify: `${roolink}user/verify/otp?otp=`,
  adminloginEndpoint: `${roolink}admin/login`,
  resendotp: `${roolink}user/resend/otp?email=`,
  logoutEndpoint: '/jwt/logout',
  pgdetailsall: `${roolink}api/getpgDetails`,
  CreatePGDetails: `${roolink}api/createPGDetails`,
  UpdatePgDetailsStatus: `${roolink}api/admin/updatePGDetails`,
  PGServiceCreation: `${roolink}api/createPGServices`,
  UpdatePGService: `${roolink}api/admin/updatePGService`,
  getUnSettleDetails: `${roolink}api/getUnSettleDetails`,
  getSettleDetails: `${roolink}api/merchant/settlementDetailsDateFilter`,
  GETdashBoardBalance: `${roolink}api/dashBoardBalance`,
  payoutwallettransfer: `${roolink}api/payout/walletTransfer`,
  payouttransactionReport: `${roolink}api/payout/transactionReport`,
  payoutaccountTransfer: `${roolink}api/payout/accountTransfer`,
  payouttransactionStatus: `${roolink}api/payout/transactionStatus`,
  payoutbalanceCheck: `${roolink}api/payout/balanceCheck`,
  changepassword: `${roolink}api/admin/passwordChange`,
  merchantbankdetails: `${roolink}api/getBankdetails`,
  profilrdetails: `${roolink}api/getMerchantDetails`,
  transactionfilter: `${roolink}api/merchant/transactionDetailsDateFilter`,
  createmerchantrequest: `${roolink}api/merchant/merchantCreateApiForCustomer`,
  allMerchantDetailsReport: `${roolink}api/admin/allMerchantDetailsReport`,
  updatebankdetails: `${roolink}api/updateBankdetails`,
  getCustomerApiRequestReport: `${roolink}api/merchant/getCustomerApiRequestReport`,
  pgDetailByPGNameAndPgId: `${roolink}api/admin/pgDetailByPGNameAndPgId`,
  updatePgConfigurationDetails: `${roolink}api/updatePgConfigurationDetails`,
  getByMerchantWisePgWiseSum: `${roolink}api/admin/getByMerchantWisePgWiseSum`,
  // search merchant
  searchmerchantListByName: `${roolink}api/admin/merchantByNameAndId`,
  getAppIdAndSecretByMerchantDetails: `${roolink}api/getAppIdAndSecretByMerchantDetails`,
  // complain api keya
  createComplaintType: `${roolink}api/admin/createComplaintType`,
  createComplaintSubType: `${roolink}api/admin/createComplaintSubType`,
  updateComplaintType: `${roolink}api/admin/updateComplaintType`,
  updateComplaintSubType: `${roolink}api/admin/updateComplaintSubType`,
  complaintDetails: `${roolink}api/admin/complaintDetails`,
   getComplaintTypeAndComplaintSubTpye: `${roolink}api/admin/getComplaintTypeAndComplaintSubTpye`,
  // create merchant api
  CreatenewMerchant: `${roolink}api/createMerchant`,
  MerchantPGDetailsAsociation: `${roolink}api/createMerchantPGDetails`,
  MerchantPGServiceAssociation: `${roolink}api/createMerchantPGServices`,
  UpdateMerchantPGStatus: `${roolink}api/admin/updateMerchantPGDetails`,
  UpdateMerchantService: `${roolink}api/admin/updateMerchantPGServices`,
  updateMerchantStatus: `${roolink}api/update/merchant/status`,
  // forgot password
  forgetPasswordGenerateOTP: `${roolink}admin/forgetPasswordGenerateOTP`,
  forgetPasswordChangeWithOTP: `${roolink}admin/forgetPasswordChangeWithOTP`,
  forgetPasswordResendOTP: `${roolink}admin/forgetPasswordResendOTP`,
  adminchangemerchantpassword: `${roolink}api/admin/changeMechantPassword`,
  // admin add bank details
  createBankDetails: `${roolink}api/admin/createBankDetails`,
  admingetmercahntbankdetails: `${roolink}api/admin/getBankdetails`,
  adminupdatemerchbankdetails: `${roolink}api/admin/updateBankdetails`,
  // merchant transaction report 
  dateWiseTxnWithParameters: `${roolink}api/admin/dateWiseTxnWithParameters`,
  // ** This will be prefixed in authorization header with token
  // ? e.g. Authorization: Bearer <token>
  // compalitmanage
  complaintDetails: `${roolink}api/admin/allListOfComplaint`,
  createComplaintType: `${roolink}api/admin/createComplaintType`,
  createComplaintSubType: `${roolink}api/admin/createComplaintSubType`,
  updateComplaintType: `${roolink}api/admin/updateComplaintType`,
  updateComplaintSubType: `${roolink}api/admin/updateComplaintSubType`,
  complaintDetailWithTicketId: `${roolink}api/admin/complaintDetails`,
  updateTicket: `${roolink}api/admin/updateTicket`,
  // refundmanagement 
  getRefundDetails: `${roolink}api/admin/getRefundDetails`,
  getRefundByMerchantIdOrStatus: `${roolink}api/admin/getRefundByMerchantIdOrStatus`,
  CreateRefundRequestByAdmin: `${roolink}api/admin/refundRequest`,
  refundUpdate: `${roolink}api/admin/refundUpdate`,
  // dashboadr api
  merchantTransactionDayDatewise: `${roolink}api/admin/merchantTransactionDayDatewise`,
  getTotalTransaction: `${roolink}api/admin/getTotalTransaction`,
  adminDetails: `${roolink}api/admin/adminDetails`,
  getTotalPayOptionTransaction: `${roolink}api/admin/getTotalPayOptionTransaction`,
  getTotalNoOfMerchants: `${roolink}api/admin/getTotalNoOfMerchants`,
  getNumberOfTxnWithStatus: `${roolink}api/admin/getNumberOfTxnWithStatus`,
  dashboardgetStatusCount: `${roolink}api/admin/getStatusCount`,
  getTrxTopReport: `${roolink}api/admin/getTrxTopReport`,
  getAllSumByPaymentOption: `${roolink}api/admin/getAllSumByPaymentOption`,
  getLastTrxMerchList: `${roolink}api/admin/getLastTrxMerchList`,
  getMinuteandCountByStatus: `${roolink}api/admin/getMinuteandCountByStatus`,
  getHourandCountStatusAndDate: `${roolink}api/admin/getHourandCountStatusAndDate`,
  getPgTypeAndCountByStatusAndDate: `${roolink}api/admin/getPgTypeAndCountByStatusAndDate`,
  getStatusAndMinuteWiseCount: `${roolink}api/admin/getStatusAndMinuteWiseCount`,
  getHourandStatusWiseCountAndDate: `${roolink}api/admin/getHourandStatusWiseCountAndDate`,
  getPGWiseMerchantList: `${roolink}api/admin/getPGWiseMerchantList`,
  getHourandStatusWiseCountAndDateAndSum: `${roolink}api/admin/getHourandStatusWiseCountAndDateAndSum`,
  // getComplaintDasboard:`${roolink}api/admin/getComplaint`,
  getComplaintDasboard: `${roolink}api/admin/getComplaint`,
  merchantStatus: `${roolink}api/admin/merchantDashboardDetails`,
  getAllTopMerchantTxn: `${roolink}api/admin/getAllTopMerchantTxn`,
  merchantTransactionLastDay: `${roolink}api/admin/merchantTransactionLastDay`,
  merchantTransactionToday: `${roolink}api/admin/merchantTransactionToday`,
  merchantTransactionCurrMonth: `${roolink}api/admin/merchantTransactionCurrMonth`,
  merchantTransactionLastMonth: `${roolink}api/admin/merchantTransactionLastMonth`,
  getTotalUnSettledAmount: `${roolink}api/admin/getTotalUnSettledAmount`,
  getTotalSettledAmount: `${roolink}api/admin/getTotalSettledAmount`,
  getTotalCancelledTransaction: `${roolink}api/admin/getTotalCancelledTransaction`,
  getTotalRefund: `${roolink}api/admin/getTotalRefund`,
  getTotalCaptured: `${roolink}api/admin/getTotalCaptured`,
  getTotalHitTransaction: `${roolink}api/admin/getTotalHitTransaction`,
  getTotalSettledAndUnsettledAmount: `${roolink}api/admin/getTotalSettledAndUnsettledAmount`,
  tokenType: 'Token',
    // payout dashboard api
  getLastTrxMerchListPayOut:`${roolink}api/admin/payout/getLastTrxMerchListPayOut`,
  getPgTypeAndCountByStatusAndDatePayOut: `${roolink}api/admin/payout/getPgTypeAndCountByStatusAndDatePayOut`,
  getStatusCountPayOut: `${roolink}api/admin/payout/getStatusCountPayOut`,
  getStatusAndMinuteWiseCountPayOut: `${roolink}api/admin/payout/getStatusAndMinuteWiseCountPayOut`,
  getHourandStatusWiseCountAndDatePayOut: `${roolink}api/admin/payout/getHourandStatusWiseCountAndDatePayOut`,
  
  //  payout Api
  getAllPayoutUsers: `${roolink}api/admin/getAllPayoutUsers`,
  getAdminDetailsSessionCheck: `${roolink}api/admin/getAdminDetails`,
  payoutwalletFilterReport: `${roolink}api/admin/walletFilterReport`,
  payouttransactionFilterReport: `${roolink}api/admin/transactionFilterReport`,
  PayoutWalletlist: `${roolink}api/admin/PayoutWalletlist`,
  payOutUserCreation: `${roolink}api/admin/payOutUserCreation`,
  WalletCreation: `${roolink}api/admin/WalletCreation`,
  WalletRecharge: `${roolink}api/admin/WalletRecharge`,
  getMainWalletList: `${roolink}api/getMainWalletList`,
  getMainWalletBalance: `${roolink}api/admin/getMainWalletBalance`,
  mainWalletRecharge: `${roolink}api/mainWalletRecharge`,
  mainWalletReversal: `${roolink}api/mainWalletReversal`,
  walletRefund: `${roolink}api/walletRefund`,
  walletReversal: `${roolink}api/walletReversal`,
  walletUpdate: `${roolink}api/walletUpdate`,
  getPayoutUserWithDetails: `${roolink}api/admin/getPayoutUserWithDetails`,
  walletUpdateStatusAndHoldAmount: `${roolink}api/payout/walletUpdateStatusAndHoldAmount`,
  // pauout merchant api
  payoutgetAllConfigPgMerchant: `${roolink}api/payout/getAllConfigPgNameMerchant`,
  findAllPayoutMerchant: `${roolink}api/payout/findAllPayoutMerchant`,
  updateStatusPayoutMerchant: `${roolink}api/payout/updateStatusPayoutMerchant`,
  // payout pg apis 
  payoutgetpglist: `${roolink}api/payout/getAllPg`,
  payoutcreatepg: `${roolink}api/payout/pgCreation`,
  payoutupdatepgconfiguration: `${roolink}api/payout/pgUpdate`,
  payoutconfigPgMerchant: `${roolink}api/payout/configPgMerchant`,
  payoutupdateConfigPgMerchant: `${roolink}api/payout/updateConfigPgMerchant`,
  // pYOUT REPORT download 
  reportgetAllPayoutReportDetails: `${roolink}api/report/getAllPayoutReportDetails`,
  payoutgeneratertransactionReport: `${roolink}api/payout/report/transactionReport`,
  payoutreportdownloadfileName: `${roolink}api/payout/report/download`,
  reportgetAllPayoutReportTransactionDownloadLinkList: `${roolink}api/report/getAllPayoutReportTransactionDownloadLinkList`,
  reportgetAllReportTrListreportName: `${roolink}api/report/getAllReportTrList`,
  // payin report download
  reportgetAllPAYINReportDetails: `${roolink}report/getAllReportTrList`,
  payingeneratertransactionReport: `${roolink}api/admin/report/transactionReport`,
  getAllPayinReportDetails: `${roolink}api/report/getAllPayinReportDetails`,
  // constantapi
  getBankList: `${roolink}api/admin/getBankList`,
  getWalletList: `${roolink}api/admin/getWalletList`,
  // IP manage
  getUserIp: `${roolink}api/admin/getUserIp`,
  updateUserIp: `${roolink}api/admin/updateUserIp`,
  // ** Value of this property will be used as key to store JWT token in storage
  // wallet managment
  rechargeRequest: `${roolink}api/rechargeRequest`,
  getAllByMerchantRecharge: `${roolink}api/getAllByMerchantRecharge`,
  rechargeMainwalletBalance: `${roolink}api/MainwalletBalance`,
  // bulk update
  getallTransactionChangeRequestpayin: `${roolink}payin/getallTransactionChangeRequest`,
  updateTransactionStatuspayin: `${roolink}api/payin/updateTransactionStatus`,
  getallTransactionChangeRequestPayout: `${roolink}api/payout/getallTransactionChangeRequest`,
  updateTransactionStatus: `${roolink}api/updateTransactionStatus`,
  // merchant walletbalance check
  merchantwalletBalancecheck: `${roolink}api/walletBalance`,
  storageTokenKeyName: 'accessToken',
  verifyotpdata: 'otpuser',
  userdatakey: 'userdatakey',
  // download report
  merchantReport: `${roolink}api/admin/merchantReport`,
  downloadFile: `${roolink}api/admin/downloadFile`,
  //   distrubutor management
  getdistrubutorlistbyadmin: `${roolink}api/findAllDistributor/informations`,
  createDistributorbyAdmin: `${roolink}api/createDistributor`,
  updatedistributorstatusbyadmin: `${roolink}api/update/distributor/status`,
  findAllMerchantsAssociatedWithADistributor: `${roolink}api/findAllMerchantsAssociatedWithADistributor/informations`,
  updateDistributorMerchantDetailsStatus: `${roolink}api/update/DistributorMerchantDetails/status`,
  createMerchantbydistributoridBYadmin: `${roolink}api/createMerchantbydistributorid`,
  updateDistributorDetailsbyAdmin: `${roolink}api/update/updateDistributorDetails`,
  // bulk updation
  getalltxnupdatefiles: `${roolink}api/get/all/txn/update/files`,
  payinupdatetxnStatusfileupload: `${roolink}api/payin/update/txnStatus/file/upload`,
  bulktransactionReversal: `${roolink}api/bulk/reversal/file/upload`,
  checktxnfileparsingstaus: `${roolink}check/txn/file/parsing/staus`,
  PAYOUTupdatetxnStatusfileupload: `${roolink}api/update/txnStatus/file/upload`,
  // admin management
  adminCreate: `${roolink}api/adminCreate`,
  getAllPGDetails: `${roolink}api/getAllPGDetails`,
  // enable call back
  enablepayincallBack:`${roolink}api/payin/callBack`,
  enablepayoutcallback:`${roolink}api/payout/callBack`,
  // update pglimit policy
  payingupdatelimitpolicy: `${roolink}api/paying/update/limit/policy`,
  // commision admin
  addmerchantcommission: `${roolink}api/add/merchant/commission`,
  updatemerchantcommission: `${roolink}api/update/merchant/commission`,
  getmerchantcommission: `${roolink}api/get/merchant/commission`,
  updatemerchantcommissionflag: `${roolink}api/update/merchant/commission/flag`,
  payingaddmodifywallet: `${roolink}api/paying/add/modify/wallet`,
  payingaddmodifybank: `${roolink}api/paying/add/modify/bank`,
  updatemerchantcommissionautoenable: `${roolink}api/update/merchant/commission/auto/enable`,
  checksessionapi: `${roolink}api/admin/getSession`
}
